# Generated by Django 5.2.1 on 2025-05-27 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('source_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=1)),
                ('type', models.CharField(choices=[('T', '선생님'), ('S', '학생')], max_length=1)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('age', models.PositiveIntegerField()),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('school_type', models.CharField(choices=[('elementary_school', 'Elementary school'), ('middle_school', 'Middle school'), ('high_school', 'High school')], max_length=255, verbose_name='학교 유형')),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.baseuser')),
                ('classroom', models.PositiveIntegerField(blank=True, max_length=20, null=True)),
                ('grade', models.PositiveIntegerField(blank=True, max_length=20, null=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='accounts.school')),
            ],
            options={
                'db_table': 'student',
            },
            bases=('accounts.baseuser',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.baseuser')),
                ('is_admin', models.BooleanField(default=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='accounts.school')),
            ],
            options={
                'db_table': 'teacher',
            },
            bases=('accounts.baseuser',),
        ),
    ]
